# Generated by Django 5.2 on 2025-07-31 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('num_matricula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Matrícula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('contacto', models.CharField(max_length=20, verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('contacto', models.CharField(max_length=20, verbose_name='Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('especialidad', models.CharField(choices=[('CARDIOLOGÍA', 'Cardiología'), ('CLÍNICO', 'Clínico'), ('GINECOLOGÍA', 'Ginecología'), ('NEUROLOGÍA', 'Neurología'), ('OFTALMOLOGÍA', 'Oftalmología'), ('GASTROENTEROLOGÍA', 'Gastroenterología')], max_length=30, verbose_name='Especialidad')),
                ('cobertura', models.CharField(max_length=30, verbose_name='Cobertura')),
                ('saldo', models.IntegerField(verbose_name='Saldo')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.paciente')),
            ],
        ),
    ]
