# Generated by Django 5.2 on 2025-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'medico'), name='unique_turno_por_medico_en_fecha_hora'),
        ),
    ]
